### ISSUE TITLE
Speed Test Speeds

### ISSUE THREAD

**Issue by plasma74** [WLAN-Pi/releases#23]
I have one of the black cube WLANPI and I am not able to see anywhere close to line rate, which I was able to see on 1.9. 

My speeds never seem to show over 400mbps.

**Comment by joshschmelzle** [comment]
We're working on a fix to address this.

**Comment by joshschmelzle** [comment]
@plasma74 this should be fixed in https://github.com/WLAN-Pi/releases/releases/tag/v2.0.0

**Comment by KB8DOA** [comment]
Same issue here.
Current v2, v1.9.1, and v1.3.1 does not resolve this.
I believe my original v1.0.0 was okay.
Where can I download v1.0.0 from?

**Comment by joshschmelzle** [comment]
@KB8DOA what hardware model are you using? and what OS/browser (this could affect the HTML5 speedtest)?

My results on a NEO2 black (512 MB RAM).

v1.9
![](https://i.imgur.com/2rWSNZg.png) 

v2
![](https://i.imgur.com/sbICePD.png)

Same test client/browser, same physical hardware, same link, just different software images.

**Comment by KB8DOA** [comment]
> 
> 
> Same issue here.
> Current v2, v1.9.1, and v1.3.1 does not resolve this.
> I believe my original v1.0.0 was okay.
> Where can I download v1.0.0 from?

Please disregard:
Something has changed on my Windows 10 with Firefox on my (once) trusty laptop...
I am seeing correct speeds now with a desktop PC with v1.9.1

**Comment by jolla** [comment]
Thanks for the update, glad to hear you were able to get it sorted.
